server:
  port: 8080
spring:
  application:
    name: HelloSpringBoot-jinzhong
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.230.130:3306/hellospringboot_jinzhong
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: cola
      password: 123456
      roles: admin
  flyway:
    baseline-on-migrate: true
    baseline-version: 20230511001
  redis:
    host: 192.168.230.130
    port: 6379
    password: 123456
    database: 0
logging:
  level:
    root: info
  file:
    name: logs/colaLog.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/colaLog-%d{yyyy-MM-dd}.%i.log
# 放行的url
security:
  ignore:
    urls:
      - /api/v1/user/login
      - /api/v1/user/save
      - /swagger-ui.html
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs
      - /webjars/**
      - /druid/**
      - /favicon.ico
